import { Navbar, Sidebar } from '@/components';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Providers } from './providers';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body
        suppressHydrationWarning={true}
        className={`${inter.className} dark:bg-dark dark:text-white`}
      >
        <Providers>
          <main className="flex flex-1 flex-col h-screen">
            <Navbar />
            <section className="lg:container lg:mx-auto flex flex-1 flex-col lg:flex-row gap-6 mt-6 dark:bg-dark ">
              <Sidebar />
              <section className="lg:w-[80%] mx-5 lg:mx-0 border-2 rounded-t-lg dark:border-borderDark ">
                {children}
              </section>
            </section>
          </main>
        </Providers>
      </body>
    </html>
  );
}
